onEvent('recipes', e => {

  e.shapeless('undergarden:gronglet', ['hostilenetworks:undergarden_prediction', '3x twilightforest:moonworm'])
  e.shapeless('3x undergarden:twistytwig', ['hostilenetworks:undergarden_prediction', '3x minecraft:string'])
  e.shapeless('3x undergarden:ditchbulb', ['hostilenetworks:undergarden_prediction', '3x minecraft:coal'])
  e.shapeless('3x undergarden:gloomgourd', ['hostilenetworks:undergarden_prediction', '3x minecraft:pumpkin'])
  e.shapeless('3x undergarden:glitterkelp', ['hostilenetworks:undergarden_prediction', '3x minecraft:kelp'])
  e.shapeless('3x minecraft:cocoa_beans', ['hostilenetworks:undergarden_prediction', '3x undergarden:underbeans'])
  e.shapeless('3x undergarden:droopvine_item', ['hostilenetworks:undergarden_prediction', '3x minecraft:sweet_berries'])

  //Complete Prediction

  function completedPrediction(input, output) { e.shapeless('hostilenetworks:' + output + '_complete_prediction', ['mekanism:alloy_atomic', Item.of('hostilenetworks:data_model', '{data_model:{data:1254,id:"hostilenetworks:' + input + '"}}')]) }
  completedPrediction("ars_nouveau/wilden_mobs", 'ars_wilden')
  completedPrediction("bat", 'bat')
  completedPrediction("bee", 'bee')
  completedPrediction("blaze", 'blaze')
  completedPrediction("blue_skies_armored_frost_spirit", 'armored_frost_spirit')
  completedPrediction("blue_skies_artificial_golem", 'artificial_golem')
  completedPrediction("blue_skies_azulfo", 'azulfo')
  completedPrediction("blue_skies_cosmic_fox", 'cosmic_fox')
  completedPrediction("blue_skies_crogre", 'crogre')
  completedPrediction("blue_skies_crynocerous", 'crynocerous')
  completedPrediction("blue_skies_crystal_camel", 'crystal_camel')
  completedPrediction("blue_skies_diophyde_prowler", 'diophyde_prowler')
  completedPrediction("blue_skies_emberback", 'emberback')
  completedPrediction("blue_skies_firefly", 'firefly')
  completedPrediction("blue_skies_frost_spirit", 'frost_spirit')
  completedPrediction("blue_skies_infested_swarmer", 'infested_swarmer')
  completedPrediction("blue_skies_nyctofly", 'nyctofly')
  completedPrediction("blue_skies_polargeist", 'polargeist')
  completedPrediction("blue_skies_reindeer", 'reindeer')
  completedPrediction("blue_skies_seclam", 'seclam')
  completedPrediction("blue_skies_shade_monitor", 'shade_monitor')
  completedPrediction("blue_skies_shrumpty", 'shrumpty')
  completedPrediction("blue_skies_snow_owl", 'snow_owl')
  completedPrediction("blue_skies_stardust_ram", 'stardust_ram')
  completedPrediction("blue_skies_stonelet", 'stonelet')
  completedPrediction("blue_skies_venom_spider", 'venom_spider')
  completedPrediction("chicken", 'chicken')
  completedPrediction("cow", 'cow')
  completedPrediction("creeper", 'creeper')
  completedPrediction("doppleganger", 'doppleganger')
  completedPrediction("drowned", 'drowned')
  completedPrediction("ender_dragon", 'ender_dragon')
  completedPrediction("enderman", 'enderman')
  completedPrediction("ghast", 'ghast')
  completedPrediction("glow_squid", 'glow_squid')
  completedPrediction("guardian", 'guardian')
  completedPrediction("hoglin", 'hoglin')
  completedPrediction("infernalexp_blackstone_dwarf", 'blackstone_dwarf')
  completedPrediction("infernalexp_blindsight", 'blindsight')
  completedPrediction("infernalexp_embody", 'embody')
  completedPrediction("infernalexp_glowsilk_moth", 'glowsilk_moth')
  completedPrediction("infernalexp_glowsquito", 'glowsquito')
  completedPrediction("infernalexp_shroomloin", 'shroomloin')
  completedPrediction("infernalexp_voline", 'voline')
  completedPrediction("infernalexp_warpbeetle", 'warpbeetle')
  completedPrediction("magma_cube", 'magma_cube')
  completedPrediction("mooshroom", 'mooshroom')
  completedPrediction("panda", 'panda')
  completedPrediction("pig", 'pig')
  completedPrediction("rabbit", 'rabbit')
  completedPrediction("sheep", 'sheep')
  completedPrediction("skeleton", 'skeleton')
  completedPrediction("slime", 'slime')
  completedPrediction("snow_golem", 'snow_golem')
  completedPrediction("spider", 'spider')
  completedPrediction("squid", 'squid')
  completedPrediction("stray", 'stray')
  completedPrediction("turtle", 'turtle')
  completedPrediction("undergarden_brute", 'brute')
  completedPrediction("undergarden_dweller", 'dweller')
  completedPrediction("undergarden_forgotten_guardian", 'forgotten_guardian')
  completedPrediction("undergarden_gloomper", 'gloomper')
  completedPrediction("undergarden_mog", 'mog')
  completedPrediction("undergarden_muncher", 'muncher')
  completedPrediction("undergarden_rotbeast", 'rotbeast')
  completedPrediction("undergarden_rotling", 'rotling')
  completedPrediction("undergarden_rotwalker", 'rotwalker')
  completedPrediction("undergarden_scintling", 'scintling')
  completedPrediction("undergarden_sploogie", 'sploogie')
  completedPrediction("undergarden_stoneborn", 'stoneborn')
  completedPrediction("warden", 'warden')
  completedPrediction("witch", 'witch')
  completedPrediction("wither_skeleton", 'wither_skeleton')
  completedPrediction("wither", 'wither')
  completedPrediction("zombie", 'zombie')
  completedPrediction("zombified_piglin", 'zombified_piglin')
  completedPrediction("cod", 'cod')
  completedPrediction("elder_guardian", 'elder_guardian')
  completedPrediction("evoker", 'evoker')
  completedPrediction("iron_golem", 'iron_golem')
  completedPrediction("phantom", 'phantom')
  completedPrediction("polar_bear", 'polar_bear')
  completedPrediction("shulker", 'shulker')
  completedPrediction("thermal_basalz", 'basalz')
  completedPrediction("thermal_blitz", 'blitz')
  completedPrediction("thermal_blizz", 'blizz')
  completedPrediction("vindicator", 'vindicator')
  completedPrediction("twilightforest/alpha_yeti", 'alpha_yeti')
  completedPrediction("twilightforest/carminite_golem", 'carminite_golem')
  completedPrediction("twilightforest/death_tome", 'death_tome')
  completedPrediction("twilightforest/deer", 'deer')
  completedPrediction("twilightforest/fire_beetle", 'fire_beetle')
  completedPrediction("twilightforest/twilight_giant", 'twilight_giant')
  completedPrediction("twilightforest/twilight_goblin", 'twilight_goblin')
  completedPrediction("twilightforest/helmet_crab", 'helmet_crab')
  completedPrediction("twilightforest/hydra", 'hydra')
  completedPrediction("twilightforest/kobold", 'kobold')
  completedPrediction("twilightforest/lich", 'lich')
  completedPrediction("twilightforest/minoshroom", 'minoshroom')
  completedPrediction("twilightforest/minotaur", 'minotaur')
  completedPrediction("twilightforest/naga", 'naga')
  completedPrediction("twilightforest/raven", 'raven')
  completedPrediction("twilightforest/redcap", 'redcap')
  completedPrediction("twilightforest/skeleton_druid", 'skeleton_druid')
  completedPrediction("twilightforest/snow_queen", 'snow_queen')
  completedPrediction("twilightforest/twilight_ice", 'twilight_ice')
  completedPrediction("twilightforest/towerwood_borer", 'towerwood_borer')
  completedPrediction("twilightforest/troll", 'troll')
  completedPrediction("twilightforest/ur_ghast", 'ur_ghast')
  completedPrediction("twilightforest/winter_wolf", 'winter_wolf')
  completedPrediction("twilightforest/wraith", 'wraith')
  completedPrediction("twilightforest/yeti", 'yeti')


})