onEvent('recipes', e => {

  e.shapeless('undergarden:gronglet', ['hostilenetworks:undergarden_prediction', '3x twilightforest:moonworm'])
  e.shapeless('3x undergarden:twistytwig', ['hostilenetworks:undergarden_prediction', '3x minecraft:string'])
  e.shapeless('3x undergarden:ditchbulb', ['hostilenetworks:undergarden_prediction', '3x minecraft:coal'])
  e.shapeless('3x undergarden:gloomgourd', ['hostilenetworks:undergarden_prediction', '3x minecraft:pumpkin'])
  e.shapeless('3x undergarden:glitterkelp', ['hostilenetworks:undergarden_prediction', '3x minecraft:kelp'])
  e.shapeless('3x minecraft:cocoa_beans', ['hostilenetworks:undergarden_prediction', '3x undergarden:underbeans'])
  e.shapeless('3x undergarden:droopvine_item', ['hostilenetworks:undergarden_prediction', '3x minecraft:sweet_berries'])

  //Complete Prediction
  function completedPrediction(input, output, amounts) {
    e.shapeless('hostilenetworks:' + output + '_complete_prediction', ['ragnamod_seven:alloy_matrix', Item.of('hostilenetworks:data_model', '{data_model:{data:' + amounts + ',id:"hostilenetworks:' + input + '"}}')])
  }
  var amounts = [1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270]
  amounts.forEach(C => {
    completedPrediction("ars_nouveau/wilden_mobs", 'ars_wilden', C)
    completedPrediction("bat", 'bat', C)
    completedPrediction("bee", 'bee', C)
    completedPrediction("blaze", 'blaze', C)
    completedPrediction("blue_skies_armored_frost_spirit", 'armored_frost_spirit', C)
    completedPrediction("blue_skies_artificial_golem", 'artificial_golem', C)
    completedPrediction("blue_skies_azulfo", 'azulfo', C)
    completedPrediction("blue_skies_cosmic_fox", 'cosmic_fox', C)
    completedPrediction("blue_skies_crogre", 'crogre', C)
    completedPrediction("blue_skies_crynocerous", 'crynocerous', C)
    completedPrediction("blue_skies_crystal_camel", 'crystal_camel', C)
    completedPrediction("blue_skies_diophyde_prowler", 'diophyde_prowler', C)
    completedPrediction("blue_skies_emberback", 'emberback', C)
    completedPrediction("blue_skies_firefly", 'firefly', C)
    completedPrediction("blue_skies_frost_spirit", 'frost_spirit', C)
    completedPrediction("blue_skies_infested_swarmer", 'infested_swarmer', C)
    completedPrediction("blue_skies_nyctofly", 'nyctofly', C)
    completedPrediction("blue_skies_polargeist", 'polargeist', C)
    completedPrediction("blue_skies_reindeer", 'reindeer', C)
    completedPrediction("blue_skies_seclam", 'seclam', C)
    completedPrediction("blue_skies_shade_monitor", 'shade_monitor', C)
    completedPrediction("blue_skies_shrumpty", 'shrumpty', C)
    completedPrediction("blue_skies_snow_owl", 'snow_owl', C)
    completedPrediction("blue_skies_stardust_ram", 'stardust_ram', C)
    completedPrediction("blue_skies_stonelet", 'stonelet', C)
    completedPrediction("blue_skies_venom_spider", 'venom_spider', C)
    completedPrediction("chicken", 'chicken', C)
    completedPrediction("cow", 'cow', C)
    completedPrediction("creeper", 'creeper', C)
    completedPrediction("doppleganger", 'doppleganger', C)
    completedPrediction("drowned", 'drowned', C)
    completedPrediction("ender_dragon", 'ender_dragon', C)
    completedPrediction("enderman", 'enderman', C)
    completedPrediction("ghast", 'ghast', C)
    completedPrediction("glow_squid", 'glow_squid', C)
    completedPrediction("guardian", 'guardian', C)
    completedPrediction("hoglin", 'hoglin', C)
    completedPrediction("infernalexp_blackstone_dwarf", 'blackstone_dwarf', C)
    completedPrediction("infernalexp_blindsight", 'blindsight', C)
    completedPrediction("infernalexp_embody", 'embody', C)
    completedPrediction("infernalexp_glowsilk_moth", 'glowsilk_moth', C)
    completedPrediction("infernalexp_glowsquito", 'glowsquito', C)
    completedPrediction("infernalexp_shroomloin", 'shroomloin', C)
    completedPrediction("infernalexp_voline", 'voline', C)
    completedPrediction("infernalexp_warpbeetle", 'warpbeetle', C)
    completedPrediction("magma_cube", 'magma_cube', C)
    completedPrediction("mooshroom", 'mooshroom', C)
    completedPrediction("panda", 'panda', C)
    completedPrediction("pig", 'pig', C)
    completedPrediction("rabbit", 'rabbit', C)
    completedPrediction("sheep", 'sheep', C)
    completedPrediction("skeleton", 'skeleton', C)
    completedPrediction("slime", 'slime', C)
    completedPrediction("snow_golem", 'snow_golem', C)
    completedPrediction("spider", 'spider', C)
    completedPrediction("squid", 'squid', C)
    completedPrediction("stray", 'stray', C)
    completedPrediction("turtle", 'turtle', C)
    completedPrediction("undergarden_brute", 'brute', C)
    completedPrediction("undergarden_dweller", 'dweller', C)
    completedPrediction("undergarden_forgotten_guardian", 'forgotten_guardian', C)
    completedPrediction("undergarden_gloomper", 'gloomper', C)
    completedPrediction("undergarden_mog", 'mog', C)
    completedPrediction("undergarden_muncher", 'muncher', C)
    completedPrediction("undergarden_rotbeast", 'rotbeast', C)
    completedPrediction("undergarden_rotling", 'rotling', C)
    completedPrediction("undergarden_rotwalker", 'rotwalker', C)
    completedPrediction("undergarden_scintling", 'scintling', C)
    completedPrediction("undergarden_sploogie", 'sploogie', C)
    completedPrediction("undergarden_stoneborn", 'stoneborn', C)
    completedPrediction("warden", 'warden', C)
    completedPrediction("witch", 'witch', C)
    completedPrediction("wither_skeleton", 'wither_skeleton', C)
    completedPrediction("wither", 'wither', C)
    completedPrediction("zombie", 'zombie', C)
    completedPrediction("zombified_piglin", 'zombified_piglin', C)
    completedPrediction("cod", 'cod', C)
    completedPrediction("elder_guardian", 'elder_guardian', C)
    completedPrediction("evoker", 'evoker', C)
    completedPrediction("iron_golem", 'iron_golem', C)
    completedPrediction("phantom", 'phantom', C)
    completedPrediction("polar_bear", 'polar_bear', C)
    completedPrediction("shulker", 'shulker', C)
    completedPrediction("thermal/basalz", 'basalz', C)
    completedPrediction("thermal/blitz", 'blitz', C)
    completedPrediction("thermal/blizz", 'blizz', C)
    completedPrediction("vindicator", 'vindicator', C)
    completedPrediction("twilightforest/alpha_yeti", 'alpha_yeti', C)
    completedPrediction("twilightforest/carminite_golem", 'carminite_golem', C)
    completedPrediction("twilightforest/death_tome", 'death_tome', C)
    completedPrediction("twilightforest/deer", 'deer', C)
    completedPrediction("twilightforest/fire_beetle", 'fire_beetle', C)
    completedPrediction("twilightforest/giant", 'twilight_giant', C)
    completedPrediction("twilightforest/goblin", 'twilight_goblin', C)
    completedPrediction("twilightforest/helmet_crab", 'helmet_crab', C)
    completedPrediction("twilightforest/hydra", 'hydra', C)
    completedPrediction("twilightforest/kobold", 'kobold', C)
    completedPrediction("twilightforest/lich", 'lich', C)
    completedPrediction("twilightforest/minoshroom", 'minoshroom', C)
    completedPrediction("twilightforest/minotaur", 'minotaur', C)
    completedPrediction("twilightforest/naga", 'naga', C)
    completedPrediction("twilightforest/raven", 'raven', C)
    completedPrediction("twilightforest/redcap", 'redcap', C)
    completedPrediction("twilightforest/skeleton_druid", 'skeleton_druid', C)
    completedPrediction("twilightforest/snow_queen", 'snow_queen', C)
    completedPrediction("twilightforest/stable_ice_core", 'twilight_ice', C)
    completedPrediction("twilightforest/towerwood_borer", 'towerwood_borer', C)
    completedPrediction("twilightforest/troll", 'troll', C)
    completedPrediction("twilightforest/ur_ghast", 'ur_ghast', C)
    completedPrediction("twilightforest/winter_wolf", 'winter_wolf', C)
    completedPrediction("twilightforest/wraith", 'wraith', C)
    completedPrediction("twilightforest/yeti", 'yeti', C)
    completedPrediction("artifacts/mimic", 'mimic', C)
  })

})