name: Feature request
description: Suggest something that should be added.
labels:
  - Feature Request
body:
  - type: markdown
    attributes:
      value: |
        Before submitting your request, check if your request has been submitted before. If it has, please don't submit a duplicate.
        If you are not using the latest version, make sure that the request has not already been fufilled.
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: Describe the feature you are requesting in a clear and concise way.
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reasons why this should be added
      description: Express why I should add your feature?
    validations:
      required: true