onEvent('block.registry', e => {

    e.create('immersiveengineering:storage_hop_graphite').displayName('Block of HOP Graphite').material('stone').hardness(5.0).tagBlock('minecraft:mineable/pickaxe')
    e.create('hostilenetworks:machine_frame').displayName('Hostile Neural Machine Frame').material('metal').hardness(5.0).tagBlock('minecraft:mineable/pickaxe')
    e.create('alchemistry:machine_frame').displayName('Alchemistry Machine Frame').material('metal').hardness(5.0).tagBlock('minecraft:mineable/pickaxe')
    e.create('cataclysm:ender_stone').displayName('Ender Stone').material('stone').hardness(5.0).tagBlock('minecraft:mineable/pickaxe')
    e.create('ftbic:silicon_block').displayName('Silicon Block').material('stone').hardness(5.0).tagBlock('minecraft:mineable/pickaxe')
    e.create('ragnamod_seven:war_block').displayName('Block of War').material('metal').hardness(5.0).tagBlock('minecraft:mineable/pickaxe')
    e.create('ragnamod_seven:famine_block').displayName('Block of Famine').material('metal').hardness(5.0).tagBlock('minecraft:mineable/pickaxe')
    e.create('ragnamod_seven:death_block').displayName('Block of Death').material('metal').hardness(5.0).tagBlock('minecraft:mineable/pickaxe')
    e.create('ragnamod_seven:conquest_block').displayName('Block of Conquest').material('metal').hardness(5.0).tagBlock('minecraft:mineable/pickaxe')
    e.create('ragnamod_seven:sculk_metal').displayName('Block of Sculk Ingot').material('metal').hardness(5.0).tagBlock('minecraft:mineable/pickaxe')
    e.create('ragnamod_seven:shub_niggurath_ingot_block').displayName('Block of Shub Niggurath Ingot').material('metal').hardness(5.0).tagBlock('minecraft:mineable/pickaxe')
    e.create('ragnamod_seven:unknown_ingot_block').displayName('Block of Unknown Ingot').material('metal').hardness(5.0).tagBlock('minecraft:mineable/pickaxe')
    e.create('ragnamod_seven:unknown_ore').displayName('Glacio Unknown Ore').material('stone').hardness(5.0).tagBlock('minecraft:mineable/pickaxe')
    e.create('ragnamod_seven:noisy_neutronium').displayName('Noisy Neutronium').material('stone').hardness(5.0).tagBlock('minecraft:mineable/pickaxe')
    e.create('ragnamod_seven:chemical_draconium_block').displayName('Chemical Draconium Block').material('stone').hardness(5.0).tagBlock('minecraft:mineable/pickaxe')
    e.create('miniutilities:stable_block').displayName('Stable Block').material('stone').hardness(5.0).tagBlock('minecraft:mineable/pickaxe')
    e.create('ragnamod_seven:singularity_silent').displayName('Singularity silent').material('portal').hardness(5.0).tagBlock('minecraft:mineable/pickaxe').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false).waterlogged()
    e.create('ragnamod_seven:ae2').displayName('Controller Online').material('stone')
    e.create('ragnamod_seven:psi_stabilizer').displayName('PSI Stabilizer').material('stone').hardness(5.0).tagBlock('minecraft:mineable/pickaxe').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false).waterlogged()
    e.create('ragnamod_seven:castle_block').displayName('Castle Block').material('stone').hardness(5.0).tagBlock('minecraft:mineable/pickaxe')


})