onEvent('item.registry', e => {

    e.create('ragnamod_seven:portal_activator').displayName('Portal Activator').maxStackSize(1)
    e.create('chickens:smashed_chicken').displayName('Smashed Chicken')
    e.create('chickens:chicken_skin').displayName('Chicken Skin')
    e.create('chickens:chicken_shell').displayName('Chicken Shell')
    e.create('chickens:nether_star_shard').displayName('§eNether Star Shard').glow(true)
    e.create('chickens:soul_chicken').displayName('Chicken Soul').glow(true)
    e.create('chickens:soul_bee').displayName('Bee Soul').glow(true)
    e.create('chemlib:draconium_compound').displayName('Draconium Compound')
    e.create('ragnamod_seven:infinity_gem').displayName('§cInfinity Gem')
    e.create('ragnamod_seven:infinity_gear').displayName('§cInfinity Gear')
    e.create('ragnamod_seven:sphere').displayName('Sphere Of All Things')
    e.create('ragnamod_seven:ignis_soul').displayName('Ignis Soul')
    e.create('ragnamod_seven:revenant_soul').displayName('Revanant Soul')
    e.create('ragnamod_seven:netherite_monstrosity_soul').displayName('Netherite Monstrosity Soul')
    e.create('ragnamod_seven:ender_golem_soul').displayName('Ender Golem Soul')
    e.create('ragnamod_seven:ender_guardian_soul').displayName('Ender Guardian Soul')
    e.create('ragnamod_seven:log_egg_component').displayName('Log Egg Component')
    e.create('gateways:catalyst_small_pearl_gate').displayName('Small Gate Catalyst')
    e.create('gateways:catalyst_medium_pearl_gate').displayName('Medium Gate Catalyst')
    e.create('gateways:catalyst_large_pearl_gate').displayName('Large Gate Catalyst')
    e.create('solarflux:photovoltaic_cell_7').displayName('Photovoltaic Cell VII')
    e.create('solarflux:photovoltaic_cell_8').displayName('Photovoltaic Cell VIII')
    e.create('solarflux:photovoltaic_cell_9').displayName('Photovoltaic Cell IX')
    e.create('solarflux:photovoltaic_cell_10').displayName('Photovoltaic Cell X')
    e.create('solarflux:photovoltaic_cell_11').displayName('Photovoltaic Cell XI')
    e.create('solarflux:photovoltaic_cell_12').displayName('Photovoltaic Cell XII')
    e.create('solarflux:photovoltaic_cell_13').displayName('Photovoltaic Cell XIII')
    e.create('hostilenetworks:blueskies_prediction').displayName('Generalized Blue Skies Prediction')
    e.create('hostilenetworks:undergarden_prediction').displayName('Generalized Undergarden Prediction')
    e.create('hostilenetworks:polymer_clay').displayName('Polymer Clay')
    e.create('ragnamod_seven:war_essence').displayName('War Essence')
    e.create('ragnamod_seven:famine_essence').displayName('Famine Essence')
    e.create('ragnamod_seven:death_essence').displayName('Death Essence')
    e.create('ragnamod_seven:conquest_essence').displayName('Conquest Essence')
    e.create('ragnamod_seven:war_essence_materialized').displayName('Materialized War Essence')
    e.create('ragnamod_seven:famine_essence_materialized').displayName('Materialized Famine Essence')
    e.create('ragnamod_seven:death_essence_materialized').displayName('Materialized Death Essence')
    e.create('ragnamod_seven:conquest_essence_materialized').displayName('Materialized Conquest Essence')
    e.create('ragnamod_seven:war_ingot').displayName('War Ingot')
    e.create('ragnamod_seven:famine_ingot').displayName('Famine Ingot')
    e.create('ragnamod_seven:death_ingot').displayName('Death Ingot')
    e.create('ragnamod_seven:conquest_ingot').displayName('Conquest Ingot')
    e.create('ragnamod_seven:war_nugget').displayName('War Nugget')
    e.create('ragnamod_seven:famine_nugget').displayName('Famine Nugget')
    e.create('ragnamod_seven:death_nugget').displayName('Death Nugget')
    e.create('ragnamod_seven:conquest_nugget').displayName('Conquest Nugget')
    e.create('ragnamod_seven:sculk_ingot').displayName('Sculk Ingot')
    e.create('ragnamod_seven:shub_niggurath_ingot').displayName('Shub Niggurath Ingot')
    e.create('ragnamod_seven:unknown_ingot').displayName('Unknown Ingot')
    e.create('ragnamod_seven:unknown_nugget').displayName('Unknown Nugget')
    e.create('ragnamod_seven:raw_unknown').displayName('Raw Unknown')
    e.create('ragnamod_seven:chemical_core').displayName('Chemical Core').glow(true)
    e.create('ragnamod_seven:ghast_cow_tear').displayName('Ghast Cow Tear')
    e.create('ragnamod_seven:ghast_cow_star').displayName('Ghast Cow Star').glow(true)
    e.create('ragnamod_seven:chemical_draconium_ingot').displayName('Chemical Draconium Ingot')
    e.create('ragnamod_seven:chemical_draconium_nugget').displayName('Chemical Draconium Nugget')
    e.create('ragnamod_seven:condensed_ingot').displayName('Condensed Ingot')
    e.create('ragnamod_seven:black_sphere').displayName('Not an Item').maxStackSize(1)
    e.create('miniutilities:stable_ingot').displayName('Stable Ingot')
    e.create('ragnamod_seven:agglomerate_matter_minecraft1').displayName('§bMinecraft\'s Agglomerate Matter #1')
    e.create('ragnamod_seven:agglomerate_matter_minecraft2').displayName('§bMinecraft\'s Agglomerate Matter #2')
    e.create('ragnamod_seven:agglomerate_matter_minecraft3').displayName('§bMinecraft\'s Agglomerate Matter #3')
    e.create('ragnamod_seven:agglomerate_matter_twilight').displayName('§bTwilight\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_blood_magic').displayName('§bBlood Magic\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_create').displayName('§bCreate\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_mekanism').displayName('§bMekanism\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_powah').displayName('§bPowah\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_botania').displayName('§bBotania\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_blue_skies').displayName('§bBlue Skies\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_space').displayName('§bSpace\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_blocky').displayName('§bBlocky\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_mobs').displayName('§bMobs\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_psi').displayName('§bPSI\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_thermal').displayName('§bThermal\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_evil_craft').displayName('§bEvil Craft\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_ae2').displayName('§bApplied Energistics\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_forbidden_arcanus').displayName('§bForbidden and Arcanus\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_undergarden').displayName('§bUndergarden\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_ftbic').displayName('§bFTBIC\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_tconstruct').displayName('§bTinkers Construct\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_ars').displayName('§bArs Nouveau\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_pneumaticcraft').displayName('§bPneumaticcraft\'s Agglomerate Matter')
    e.create('ragnamod_seven:agglomerate_matter_tech').displayName('§bTech\'s Agglomerate Matter')
    e.create('ragnamod_seven:creative_augment_base').displayName('Creative Augmente Base')
    e.create('ragnamod_seven:holy_powders').displayName('Holy Magic Powders')
    e.create('ragnamod_seven:creative_tc_crystal').displayName("Creative Tinkers' Crystal").glow(true).maxStackSize(1)
    e.create('ragnamod_seven:alloy_matrix').displayName("§cMatrix Alloy").glow(true).maxStackSize(1)
    e.create('ragnamod_seven:solid_nuclear_waste').displayName("Solid Nuclear Waste")
    e.create('ragnamod_seven:bloody_addon').displayName("Bloody Addon").maxStackSize(4)
    e.create('ragnamod_seven:blood_data_model').displayName("Blood Data Model").maxStackSize(1)
    e.create('ragnamod_seven:blood_infused_data_model').displayName("Blood Infused Data Model").maxStackSize(1)
    e.create('ragnamod_seven:deeply_blood_infused_data_model').displayName("Deeply Blood Infused Data Model").maxStackSize(1)
    e.create('ragnamod_seven:speed_addon').displayName("Speed Addon").maxStackSize(8)
    e.create('ragnamod_seven:chaos_dust').displayName("Chaos Dust")
    e.create('ragnamod_seven:unpredictable_dust').displayName("Unpredictable Dust").glow(true)
    e.create('ragnamod_seven:questionable_mixture').displayName("Questionable Mixture")
    e.create('ragnamod_seven:strange_mixture').displayName("Strange Mixture")
    e.create('ragnamod_seven:sickening_mixture').displayName("Sickening Mixture")
    e.create('thermal:press_rod_die').displayName("Rodworking Die").maxStackSize(1)
    e.create('thermal:press_wire_die').displayName("Wireworking Die").maxStackSize(1)
    e.create('bloodmagic:dawnscribetool').displayName("Inscription Tool: Dawn").maxStackSize(1).maxDamage(40)
})