onEvent('item.registry', e => {

    e.create('portal_activator').displayName('Portal Activator').maxStackSize(1)
    e.create('chickens:dead_chicken').displayName('Dead Chicken').maxStackSize(1)
    e.create('chickens:chicken_skin').displayName('Chicken Skin').maxStackSize(1)
    e.create('chickens:chicken_shell').displayName('Chicken Shell').maxStackSize(1)
    e.create('chickens:nether_star_shard').displayName('§eNether Star Shard').glow(true)
    e.create('chemlib:draconium_compound').displayName('Draconium Compound')
    e.create('ragnamod_seven:gold_singularity').displayName('§eGold Singularity')
    e.create('ragnamod_seven:fluix_singularity').displayName('§eFluix Singularity')
    e.create('ragnamod_seven:algal_singularity').displayName('§eAlgal Singularity')
    e.create('ragnamod_seven:cerebral_singularity').displayName('§eCerebral Singularity')
    e.create('ragnamod_seven:netherbrass_singularity').displayName('§eNether Brass Singularity')
    e.create('ragnamod_seven:oraclejelly_singularity').displayName('§eOracle Jelly Singularity')
    e.create('ragnamod_seven:sunmetal_singularity').displayName('§eSunmetal Singularity')
    e.create('ragnamod_seven:wardstone_singularity').displayName('§eWardstone Singularity')
    e.create('ragnamod_seven:sourcegem_singularity').displayName('§eSource Gem Singularity')
    e.create('ragnamod_seven:calorite_singularity').displayName('§eCalorite Singularity')
    e.create('ragnamod_seven:desh_singularity').displayName('§eDesh Singularity')
    e.create('ragnamod_seven:ostrum_singularity').displayName('§eOstrum Singularity')
    e.create('ragnamod_seven:corrosivewill_singularity').displayName('§eCorrosive Will Singularity')
    e.create('ragnamod_seven:demonwill_singularity').displayName('§eDemon Will Singularity')
    e.create('ragnamod_seven:destructivewill_singularity').displayName('§eDestructive Will Singularity')
    e.create('ragnamod_seven:steadfaswill_singularity').displayName('§eSteadfast Will Singularity')
    e.create('ragnamod_seven:vengefulwill_singularity').displayName('§eVengeful Will Singularity')
    e.create('ragnamod_seven:diopside_singularity').displayName('§eDiopside Singularity')
    e.create('ragnamod_seven:pyrope_singularity').displayName('§ePyrope Singularity')
    e.create('ragnamod_seven:aquite_singularity').displayName('§eAquite Singularity')
    e.create('ragnamod_seven:charoite_singularity').displayName('§eCharoite Singularity')
    e.create('ragnamod_seven:falsite_singularity').displayName('§eFalsite Singularity')
    e.create('ragnamod_seven:horizonite_singularity').displayName('§eHorizonite Singularity')
    e.create('ragnamod_seven:ventium_singularity').displayName('§eVentium Singularity')
    e.create('ragnamod_seven:livingrock_singularity').displayName('§eLivingrock Singularity')
    e.create('ragnamod_seven:livingwood_singularity').displayName('§eLivingwood Singularity')
    e.create('ragnamod_seven:manadiamond_singularity').displayName('§eMana Diamond Singularity')
    e.create('ragnamod_seven:pixie_singularity').displayName('§ePixie Singularity')
    e.create('ragnamod_seven:constructionpaste_singularity').displayName('§eConstruction Paste Singularity')
    e.create('ragnamod_seven:pendorite_singularity').displayName('§ePendorite Singularity')
    e.create('ragnamod_seven:compactmachinewall_singularity').displayName('§eCompact Machine Wall Singularity')
    e.create('ragnamod_seven:electrontube_singularity').displayName('§eElectron Tube Singularity')
    e.create('ragnamod_seven:precisionmechanism_singularity').displayName('§ePrecision Mechanism Singularity')
    e.create('ragnamod_seven:zinc_singularity').displayName('§eZinc Singularity')
    e.create('ragnamod_seven:sturdysheet_singularity').displayName('§eSturdy Sheet Singularity')
    e.create('ragnamod_seven:heatengine_singularity').displayName('§eHeat Engine Singularity')
    e.create('ragnamod_seven:hydraulicengine_singularity').displayName('§eHydraulic Engine Singularity')
    e.create('ragnamod_seven:steamengine_singularity').displayName('§eSteam Engine Singularity')
    e.create('ragnamod_seven:castiron_singularity').displayName('§eCast Iron Singularity')
    e.create('ragnamod_seven:industrialiron_singularity').displayName('§eIndustrial Iron Singularity')
    e.create('ragnamod_seven:bloodpotash_singularity').displayName('§eBlood Potash Singularity')
    e.create('ragnamod_seven:darkpower_singularity').displayName('§eDark Power Singularity')
    e.create('ragnamod_seven:arcanecrystal_singularity').displayName('§eArcane Crystal Singularity')
    e.create('ragnamod_seven:darknetherstar_singularity').displayName('§eDark Nether Star Singularity')
    e.create('ragnamod_seven:mundabitur_singularity').displayName('§eMundabitur Singularity')
    e.create('ragnamod_seven:antimatter_singularity').displayName('§eAntimatter Singularity')
    e.create('ragnamod_seven:compressedcoalball_singularity').displayName('§eCompressed Coal Ball Singularity')
    e.create('ragnamod_seven:ftbroteinbar_singularity').displayName('§eFeed The Beast™ Protein Bar Singularity')
    e.create('ragnamod_seven:scrap_singularity').displayName('§eScrap Singularity')
    e.create('ragnamod_seven:fertilizer_singularity').displayName('§eFertilizer Singularity')
    e.create('ragnamod_seven:pinkslime_singularity').displayName('§ePink Slime Singularity')
    e.create('ragnamod_seven:plastic_singularity').displayName('§ePlastic Singularity')
    e.create('ragnamod_seven:glowcoke_singularity').displayName('§eGlowcoke Singularity')
    e.create('ragnamod_seven:logicdirector_singularity').displayName('§eLogic Director Singularity')
    e.create('ragnamod_seven:variablecard_singularity').displayName('§eVariable Card Singularity')
    e.create('ragnamod_seven:electrolytic_singularity').displayName('§eElectrolytic Singularity')
    e.create('ragnamod_seven:mekasuitmodule_singularity').displayName('§eMekasuit Module Singularity')
    e.create('ragnamod_seven:osmium_singularity').displayName('§eOsmium Singularity')
    e.create('ragnamod_seven:uranium_singularity').displayName('§eUranium Singularity')
    e.create('ragnamod_seven:reprocessedfissilefragment_singularity').displayName('§eReprocessed Fissile Fragment Singularity')
    e.create('ragnamod_seven:amethyst_singularity').displayName('§eAmethyst Singularity')
    e.create('ragnamod_seven:coal_singularity').displayName('§eCoal Singularity')
    e.create('ragnamod_seven:diamond_singularity').displayName('§eDiamond Singularity')
    e.create('ragnamod_seven:emerald_singularity').displayName('§eEmerald Singularity')
    e.create('ragnamod_seven:redstone_singularity').displayName('§eRedstone Singularity')
    e.create('ragnamod_seven:enderpearl_singularity').displayName('§eEnder Pearl Singularity')
    e.create('ragnamod_seven:glowstone_singularity').displayName('§eGlowstone Singularity')
    e.create('ragnamod_seven:lapislazuli_singularity').displayName('§eLapis Lazuli Singularity')
    e.create('ragnamod_seven:netheritescrap_singularity').displayName('§eNetherite Scrap Singularity')
    e.create('ragnamod_seven:quartz_singularity').displayName('§eQuartz Singularity')
    e.create('ragnamod_seven:copper_singularity').displayName('§eCopper Singularity')
    e.create('ragnamod_seven:iron_singularity').displayName('§eIron Singularity')
    e.create('ragnamod_seven:jellybaby_singularity').displayName('§eJelly Baby Singularity')
    e.create('ragnamod_seven:infusedrock_singularity').displayName('§eInfused Rock Singularity')
    e.create('ragnamod_seven:spiritattunedgem_singularity').displayName('§eSpirit Attuned Gem Singularity')
    e.create('ragnamod_seven:capacitor_singularity').displayName('§eCapacitor Singularity')
    e.create('ragnamod_seven:glycerol_singularity').displayName('§eGlycerol Singularity')
    e.create('ragnamod_seven:transistor_singularity').displayName('§eTransistor Singularity')
    e.create('ragnamod_seven:blazingcrystal_singularity').displayName('§eBlazing Crystal Singularity')
    e.create('ragnamod_seven:nioticcrystal_singularity').displayName('§eNiotic Crystal Singularity')
    e.create('ragnamod_seven:nitrocrystal_singularity').displayName('§eNitro Crystal Singularity')
    e.create('ragnamod_seven:spiritedcrystal_singularity').displayName('§eSpirited Crystal Singularity')
    e.create('ragnamod_seven:energizedsteel_singularity').displayName('§eEnergized Steel Singularity')
    e.create('ragnamod_seven:uraninite_singularity').displayName('§eUraninite Singularity')
    e.create('ragnamod_seven:ebony_singularity').displayName('§eEbony Singularity')
    e.create('ragnamod_seven:ivory_singularity').displayName('§eIvory Singularity')
    e.create('ragnamod_seven:psigem_singularity').displayName('§ePsigem Singularity')
    e.create('ragnamod_seven:catalyzinggland_singularity').displayName('§eCatalyzing Gland Singularity')
    e.create('ragnamod_seven:chelicerae_singularity').displayName('§eChelicerae Singularity')
    e.create('ragnamod_seven:frozencore_singularity').displayName('§eFrozen Core Singularity')
    e.create('ragnamod_seven:moltencore_singularity').displayName('§eMolten Core Singularity')
    e.create('ragnamod_seven:nebulousheart_singularity').displayName('§eNebulous Heart Singularity')
    e.create('ragnamod_seven:ribbone_singularity').displayName('§eRib Bone Singularity')
    e.create('ragnamod_seven:zombieheart_singularity').displayName('§eZombie Heart Singularity')
    e.create('ragnamod_seven:soulpowder_singularity').displayName('§eSoul Powder Singularity')
    e.create('ragnamod_seven:cobalt_singularity').displayName('§eCobalt Singularity')
    e.create('ragnamod_seven:basalz_singularity').displayName('§eBasalz Singularity')
    e.create('ragnamod_seven:blitz_singularity').displayName('§eBlitz Singularity')
    e.create('ragnamod_seven:blizz_singularity').displayName('§eBlizz Singularity')
    e.create('ragnamod_seven:bitumen_singularity').displayName('§eBitumen Singularity')
    e.create('ragnamod_seven:cinnabar_singularity').displayName('§eCinnabar Singularity')
    e.create('ragnamod_seven:niter_singularity').displayName('§eNiter Singularity')
    e.create('ragnamod_seven:lead_singularity').displayName('§eLead Singularity')
    e.create('ragnamod_seven:nickel_singularity').displayName('§eNickel Singularity')
    e.create('ragnamod_seven:silver_singularity').displayName('§eSilver Singularity')
    e.create('ragnamod_seven:tin_singularity').displayName('§eTin Singularity')
    e.create('ragnamod_seven:rosin_singularity').displayName('§eRosin Singularity')
    e.create('ragnamod_seven:slag_singularity').displayName('§eSlag Singularity')
    e.create('ragnamod_seven:sulfur_singularity').displayName('§eSulfur Singularity')
    e.create('ragnamod_seven:bauxite_singularity').displayName('§eBauxite Singularity')
    e.create('ragnamod_seven:kepu_singularity').displayName('§eKepu Singularity')
    e.create('ragnamod_seven:alphayeti_singularity').displayName('§eAlpha Yeti Singularity')
    e.create('ragnamod_seven:carminite_singularity').displayName('§eCarminite Singularity')
    e.create('ragnamod_seven:castlebrick_singularity').displayName('§eCastle Brick Singularity')
    e.create('ragnamod_seven:magicbeans_singularity').displayName('§eMagic Beans Singularity')
    e.create('ragnamod_seven:ironwood_singularity').displayName('§eIronwood Singularity')
    e.create('ragnamod_seven:steeleaf_singularity').displayName('§eSteeleaf Singularity')
    e.create('ragnamod_seven:depthrock_singularity').displayName('§eDepthrock Pebble Singularity')
    e.create('ragnamod_seven:cloggrum_singularity').displayName('§eCloggrum Singularity')
    e.create('ragnamod_seven:froststeel_singularity').displayName('§eFroststeel Singularity')
    e.create('ragnamod_seven:sculk_singularity').displayName('§eSculk Singularity')
    e.create('ragnamod_seven:utherium_singularity').displayName('§eUtherium Singularity')
    e.create('ragnamod_seven:forgotten_singularity').displayName('§eForgotten Singularity')
    e.create('ragnamod_seven:regalium_singularity').displayName('§eRegalium Singularity')
    e.create('ragnamod_seven:raw_materials').displayName('§bRaw Materials Singularity')
    e.create('ragnamod_seven:magic').displayName('§bMagic Singularity')
    e.create('ragnamod_seven:undergarden').displayName('§bUndergarden Singularity')
    e.create('ragnamod_seven:tech').displayName('§bTech Singularity')
    e.create('ragnamod_seven:ftbic').displayName('§bFTBIC Singularity')
    e.create('ragnamod_seven:pneumaticcraft').displayName('§bPneumaticcraft Singularity')
    e.create('ragnamod_seven:industrial').displayName('§bIndustrial Singularity')
    e.create('ragnamod_seven:forbidden').displayName('§bForbidden Arcanus Singularity')
    e.create('ragnamod_seven:vanilla').displayName('§bVanilla Singularity')
    e.create('ragnamod_seven:special_bricks').displayName('§bSpecial Bricks Singularity')
    e.create('ragnamod_seven:mobs').displayName('§bMobs Singularity')
    e.create('ragnamod_seven:psi').displayName('§bPSI Singularity')
    e.create('ragnamod_seven:thermal').displayName('§bThermal Singularity')
    e.create('ragnamod_seven:evil_craft').displayName('§bEvil Craft Singularity')
    e.create('ragnamod_seven:twilight').displayName('§bTwilight Singularity')
    e.create('ragnamod_seven:blood_magic').displayName('§bBlood Magic Singularity')
    e.create('ragnamod_seven:create').displayName('§bCreate Singularity')
    e.create('ragnamod_seven:meka').displayName('§bMeka Singularity')
    e.create('ragnamod_seven:powah').displayName('§bPowah Singularity')
    e.create('ragnamod_seven:botania').displayName('§bBotania Singularity')
    e.create('ragnamod_seven:blue_skies').displayName('§bBlue Skies Singularity')
    e.create('ragnamod_seven:space').displayName('§bSpace Singularity')
    e.create('ragnamod_seven:infinity_gem').displayName('§cInfinity Gem')
    e.create('ragnamod_seven:sphere').displayName('Sphere Of All Things')
    e.create('ragnamod_seven:neutronium_nutritious_compound').displayName('Nutritious Compound of Neutronium')
    e.create('gateways:catalyst_small_pearl_gate').displayName('Small Gate Catalyst')
    e.create('gateways:catalyst_medium_pearl_gate').displayName('Medium Gate Catalyst')
    e.create('gateways:catalyst_large_pearl_gate').displayName('Large Gate Catalyst')
    e.create('solarflux:photovoltaic_cell_7').displayName('Photovoltaic Cell VII')
    e.create('solarflux:photovoltaic_cell_8').displayName('Photovoltaic Cell VIII')
    e.create('solarflux:photovoltaic_cell_9').displayName('Photovoltaic Cell XI')
    e.create('solarflux:photovoltaic_cell_10').displayName('Photovoltaic Cell X')
    e.create('solarflux:photovoltaic_cell_11').displayName('Photovoltaic Cell XI')
    e.create('solarflux:photovoltaic_cell_12').displayName('Photovoltaic Cell XII')
    e.create('solarflux:photovoltaic_cell_13').displayName('Photovoltaic Cell XIII')
})