onEvent('item.registry', e => {

    e.create('ragnamod_seven:gold_singularity').displayName('§eGold Singularity')
    e.create('ragnamod_seven:fluix_singularity').displayName('§eFluix Singularity')
    e.create('ragnamod_seven:cerebral_singularity').displayName('§eCerebral Singularity')
    e.create('ragnamod_seven:netherbrass_singularity').displayName('§eNether Brass Singularity')
    e.create('ragnamod_seven:sunmetal_singularity').displayName('§eSunmetal Singularity')
    e.create('ragnamod_seven:wardstone_singularity').displayName('§eWardstone Singularity')
    e.create('ragnamod_seven:calorite_singularity').displayName('§eCalorite Singularity')
    e.create('ragnamod_seven:desh_singularity').displayName('§eDesh Singularity')
    e.create('ragnamod_seven:ostrum_singularity').displayName('§eOstrum Singularity')
    e.create('ragnamod_seven:corrosivewill_singularity').displayName('§eCorrosive Will Singularity')
    e.create('ragnamod_seven:demonwill_singularity').displayName('§eDemon Will Singularity')
    e.create('ragnamod_seven:destructivewill_singularity').displayName('§eDestructive Will Singularity')
    e.create('ragnamod_seven:steadfaswill_singularity').displayName('§eSteadfast Will Singularity')
    e.create('ragnamod_seven:vengefulwill_singularity').displayName('§eVengeful Will Singularity')
    e.create('ragnamod_seven:aquite_singularity').displayName('§eAquite Singularity')
    e.create('ragnamod_seven:charoite_singularity').displayName('§eCharoite Singularity')
    e.create('ragnamod_seven:falsite_singularity').displayName('§eFalsite Singularity')
    e.create('ragnamod_seven:horizonite_singularity').displayName('§eHorizonite Singularity')
    e.create('ragnamod_seven:ventium_singularity').displayName('§eVentium Singularity')
    e.create('ragnamod_seven:livingrock_singularity').displayName('§eLivingrock Singularity')
    e.create('ragnamod_seven:livingwood_singularity').displayName('§eLivingwood Singularity')
    e.create('ragnamod_seven:manadiamond_singularity').displayName('§eMana Diamond Singularity')
    e.create('ragnamod_seven:pixie_singularity').displayName('§ePixie Singularity')
    e.create('ragnamod_seven:compactmachinewall_singularity').displayName('§eCompact Machine Wall Singularity')
    e.create('ragnamod_seven:electrontube_singularity').displayName('§eElectron Tube Singularity')
    e.create('ragnamod_seven:precisionmechanism_singularity').displayName('§ePrecision Mechanism Singularity')
    e.create('ragnamod_seven:heatengine_singularity').displayName('§eHeat Engine Singularity')
    e.create('ragnamod_seven:hydraulicengine_singularity').displayName('§eHydraulic Engine Singularity')
    e.create('ragnamod_seven:steamengine_singularity').displayName('§eSteam Engine Singularity')
    e.create('ragnamod_seven:bloodpotash_singularity').displayName('§eBlood Potash Singularity')
    e.create('ragnamod_seven:darkpower_singularity').displayName('§eDark Power Singularity')
    e.create('ragnamod_seven:arcanecrystal_singularity').displayName('§eArcane Crystal Singularity')
    e.create('ragnamod_seven:darknetherstar_singularity').displayName('§eDark Nether Star Singularity')
    e.create('ragnamod_seven:mundabitur_singularity').displayName('§eMundabitur Singularity')
    e.create('ragnamod_seven:antimatter_singularity').displayName('§eAntimatter Singularity')
    e.create('ragnamod_seven:compressedcoalball_singularity').displayName('§eCompressed Coal Ball Singularity')
    e.create('ragnamod_seven:ftbroteinbar_singularity').displayName('§eFeed The Beast™ Protein Bar Singularity')
    e.create('ragnamod_seven:scrap_singularity').displayName('§eScrap Singularity')
    e.create('ragnamod_seven:fertilizer_singularity').displayName('§eFertilizer Singularity')
    e.create('ragnamod_seven:plastic_singularity').displayName('§ePlastic Singularity')
    e.create('ragnamod_seven:logicdirector_singularity').displayName('§eLogic Director Singularity')
    e.create('ragnamod_seven:variablecard_singularity').displayName('§eVariable Card Singularity')
    e.create('ragnamod_seven:electrolytic_singularity').displayName('§eElectrolytic Singularity')
    e.create('ragnamod_seven:mekasuitmodule_singularity').displayName('§eMekasuit Module Singularity')
    e.create('ragnamod_seven:osmium_singularity').displayName('§eOsmium Singularity')
    e.create('ragnamod_seven:reprocessedfissilefragment_singularity').displayName('§eReprocessed Fissile Fragment Singularity')
    e.create('ragnamod_seven:amethyst_singularity').displayName('§eAmethyst Singularity')
    e.create('ragnamod_seven:coal_singularity').displayName('§eCoal Singularity')
    e.create('ragnamod_seven:diamond_singularity').displayName('§eDiamond Singularity')
    e.create('ragnamod_seven:emerald_singularity').displayName('§eEmerald Singularity')
    e.create('ragnamod_seven:redstone_singularity').displayName('§eRedstone Singularity')
    e.create('ragnamod_seven:enderpearl_singularity').displayName('§eEnder Pearl Singularity')
    e.create('ragnamod_seven:glowstone_singularity').displayName('§eGlowstone Singularity')
    e.create('ragnamod_seven:lapislazuli_singularity').displayName('§eLapis Lazuli Singularity')
    e.create('ragnamod_seven:netheritescrap_singularity').displayName('§eNetherite Scrap Singularity')
    e.create('ragnamod_seven:quartz_singularity').displayName('§eQuartz Singularity')
    e.create('ragnamod_seven:copper_singularity').displayName('§eCopper Singularity')
    e.create('ragnamod_seven:iron_singularity').displayName('§eIron Singularity')
    e.create('ragnamod_seven:capacitor_singularity').displayName('§eCapacitor Singularity')
    e.create('ragnamod_seven:glycerol_singularity').displayName('§eGlycerol Singularity')
    e.create('ragnamod_seven:transistor_singularity').displayName('§eTransistor Singularity')
    e.create('ragnamod_seven:blazingcrystal_singularity').displayName('§eBlazing Crystal Singularity')
    e.create('ragnamod_seven:nioticcrystal_singularity').displayName('§eNiotic Crystal Singularity')
    e.create('ragnamod_seven:nitrocrystal_singularity').displayName('§eNitro Crystal Singularity')
    e.create('ragnamod_seven:spiritedcrystal_singularity').displayName('§eSpirited Crystal Singularity')
    e.create('ragnamod_seven:energizedsteel_singularity').displayName('§eEnergized Steel Singularity')
    e.create('ragnamod_seven:uranium_singularity').displayName('§eUranium Singularity')
    e.create('ragnamod_seven:oracle_jelly_singularity').displayName('§eOracle Jelly Singularity')
    e.create('ragnamod_seven:ebony_singularity').displayName('§eEbony Singularity')
    e.create('ragnamod_seven:ivory_singularity').displayName('§eIvory Singularity')
    e.create('ragnamod_seven:psigem_singularity').displayName('§ePsigem Singularity')
    e.create('ragnamod_seven:catalyzinggland_singularity').displayName('§eCatalyzing Gland Singularity')
    e.create('ragnamod_seven:frozencore_singularity').displayName('§eFrozen Core Singularity')
    e.create('ragnamod_seven:moltencore_singularity').displayName('§eMolten Core Singularity')
    e.create('ragnamod_seven:nebulousheart_singularity').displayName('§eNebulous Heart Singularity')
    e.create('ragnamod_seven:zombieheart_singularity').displayName('§eZombie Heart Singularity')
    e.create('ragnamod_seven:cobalt_singularity').displayName('§eCobalt Singularity')
    e.create('ragnamod_seven:basalz_singularity').displayName('§eBasalz Singularity')
    e.create('ragnamod_seven:blitz_singularity').displayName('§eBlitz Singularity')
    e.create('ragnamod_seven:blizz_singularity').displayName('§eBlizz Singularity')
    e.create('ragnamod_seven:rosin_singularity').displayName('§eRosin Singularity')
    e.create('ragnamod_seven:slag_singularity').displayName('§eSlag Singularity')
    e.create('ragnamod_seven:alphayeti_singularity').displayName('§eAlpha Yeti Singularity')
    e.create('ragnamod_seven:carminite_singularity').displayName('§eCarminite Singularity')
    e.create('ragnamod_seven:magicbeans_singularity').displayName('§eMagic Beans Singularity')
    e.create('ragnamod_seven:ironwood_singularity').displayName('§eIronwood Singularity')
    e.create('ragnamod_seven:steeleaf_singularity').displayName('§eSteeleaf Singularity')
    e.create('ragnamod_seven:cloggrum_singularity').displayName('§eCloggrum Singularity')
    e.create('ragnamod_seven:froststeel_singularity').displayName('§eFroststeel Singularity')
    e.create('ragnamod_seven:sculk_singularity').displayName('§eSculk Singularity')
    e.create('ragnamod_seven:utherium_singularity').displayName('§eUtherium Singularity')
    e.create('ragnamod_seven:forgotten_singularity').displayName('§eForgotten Singularity')
    e.create('ragnamod_seven:regalium_singularity').displayName('§eRegalium Singularity')
    e.create('ragnamod_seven:cheese_singularity').displayName('§eCheese Singularity')
    e.create('ragnamod_seven:ice_shard_singularity').displayName('§eIce Shard Singularity')
    e.create('ragnamod_seven:alfsteel_singularity').displayName('§eAlfsteel Singularity')
    e.create('ragnamod_seven:honeycomb_singularity').displayName('§eHoneycomb Singularity')
    e.create('ragnamod_seven:black_psimetal_singularity').displayName('§eDark PSImetal Singularity')
    e.create('ragnamod_seven:white_psimetal_singularity').displayName('§eBright PSImetal Singularity')
    e.create('ragnamod_seven:blood_waxed_coal_singularity').displayName('§eBlood Waxed Coal Singularity')
    e.create('ragnamod_seven:condensed_blood_singularity').displayName('§eCondensed Blood Singularity')
    e.create('ragnamod_seven:dark_gem_singularity').displayName('§eDark Gem Singularity')
    e.create('ragnamod_seven:certus_quartz_crystal_singularity').displayName('§eCertus Quartz Crystal Singularity')
    e.create('ragnamod_seven:logic_processor_singularity').displayName('§eLogic Processor Singularity')
    e.create('ragnamod_seven:calculation_processor_singularity').displayName('§eCalculation Processor Singularity')
    e.create('ragnamod_seven:engineering_processor_singularity').displayName('§eEngineering Processor Singularity')
    e.create('ragnamod_seven:rune_singularity').displayName('§eRune Singularity')
    e.create('ragnamod_seven:dark_matter_singularity').displayName('§eDark Matter Singularity')
    e.create('ragnamod_seven:silicon_singularity').displayName('§eSilicon Singularity')
    e.create('ragnamod_seven:amethyst_bronze_singularity').displayName('§eAmethyst Bronze Singularity')
    e.create('ragnamod_seven:manyullyn_singularity').displayName('§eManyullyn Singularity')
    e.create('ragnamod_seven:seared_brick_singularity').displayName('§eSeared Brick Singularity')
    e.create('ragnamod_seven:scorched_brick_singularity').displayName('§eScorched Brick Singularity')
    e.create('ragnamod_seven:air_essence_singularity').displayName('§eAir Essence Singularity')
    e.create('ragnamod_seven:earth_essence_singularity').displayName('§eEarth Essence Singularity')
    e.create('ragnamod_seven:fire_essence_singularity').displayName('§eFire Essence Singularity')
    e.create('ragnamod_seven:water_essence_singularity').displayName('§eWater Essence Singularity')
    e.create('ragnamod_seven:abjuration_essence_singularity').displayName('§eAbjuration Essence Singularity')
    e.create('ragnamod_seven:programming_puzzle_singularity').displayName('§eProgramming Puzzle Singularity')
    e.create('ragnamod_seven:iron_compressed_singularity').displayName('§eCompressed Iron Singularity')

})