
#General addon settings
[general]
	#Method of gaining modifier slots for tools.
	#Allowed Values: NONE, PREDEFINED_ORDER, RANDOM
	toolsSlotGainingMethod = "RANDOM"
	#Method of gaining modifier slots for ranged weapons.
	#Allowed Values: NONE, PREDEFINED_ORDER, RANDOM
	rangedSlotGainingMethod = "RANDOM"
	#Method of gaining modifier slots for armor.
	#Allowed Values: NONE, PREDEFINED_ORDER, RANDOM
	armorSlotGainingMethod = "RANDOM"
	#Method of gaining stats for tools.
	#Allowed Values: NONE, PREDEFINED_ORDER, RANDOM
	toolsStatGainingMethod = "RANDOM"
	#Method of gaining stats for tools.
	#Allowed Values: NONE, PREDEFINED_ORDER, RANDOM
	rangedStatGainingMethod = "RANDOM"
	#Method of gaining stats for armor.
	#Allowed Values: NONE, PREDEFINED_ORDER, RANDOM
	armorStatGainingMethod = "RANDOM"
	#Maximum tool level that could be achieved. If set to 0 there is no upper limit.
	#Range: > 0
	maxLevel = 15
	#Base amount of experience required to reach next level.
	#Range: > 1
	baseExperience = 500
	#How much the amount of experience required to reach next level will be multiplied per level.
	#Range: 1.0 ~ 10.0
	requiredXpMultiplier = 1.0
	#Additional multiplier for broad tools for experience required to level up.
	#Range: 1.0 ~ 10.0
	broadToolRequiredXpMultiplier = 3.0

	#Modifier slots settings
	[general.slots]
		#Set of modifier slot types from which random slot will be awarded when leveling up tools.
		#If empty default pool will be used (upgrade, upgrade, upgrade, upgrade, ability). 80% chance for upgrade and 20% chance for ability.
		#Allowed values: upgrade, ability, soul, defense
		toolsSlotTypeRandomPool = ["upgrade", "ability"]
		#List of modifier slot types (in order) that will be awarded when leveling up tools. If level is higher than list size the mod will start over.
		#If empty default order will be used (upgrade, upgrade, upgrade, ability, upgrade).
		#Allowed values: upgrade, ability, soul, defense
		toolsSlotTypeOrder = ["upgrade", "upgrade", "upgrade", "ability", "upgrade"]
		#Set of modifier slot types from which random slot will be awarded when leveling up ranged weapons.
		#If empty default pool will be used (upgrade, upgrade, upgrade, upgrade, ability). 80% chance for upgrade and 20% chance for ability.
		#Allowed values: upgrade, ability, soul, defense
		rangedSlotTypeRandomPool = ["upgrade", "ability"]
		#List of modifier slot types (in order) that will be awarded when leveling up ranged weapons. If level is higher than list size the mod will start over.
		#If empty default order will be used (upgrade, upgrade, upgrade, ability, upgrade).
		#Allowed values: upgrade, ability, soul, defense
		rangedSlotTypeOrder = ["upgrade", "upgrade", "upgrade", "ability", "upgrade"]
		#Set of modifier slot types from which random slot will be awarded when leveling up armor.
		#If empty default pool will be used (upgrade, upgrade, defense, defense, ability).
		#Allowed values: upgrade, ability, soul, defense
		armorSlotTypeRandomPool = ["upgrade", "ability"]
		#List of modifier slot types (in order) that will be awarded when leveling up armor. If level is higher than list size the mod will start over.
		#If empty default order will be used (upgrade, defense, upgrade, ability, defense).
		#Allowed values: upgrade, ability, soul, defense
		armorSlotTypeOrder = ["upgrade", "defense", "upgrade", "ability", "defense"]

	#Stats settings
	[general.stats]
		#Set of stat types from which random stat will be awarded when leveling up tools.
		#If empty default pool will be used (durability, attackDamage, attackSpeed, miningSpeed). 25% chance for every stat.
		#Allowed values: durability, attackDamage, attackSpeed, miningSpeed
		toolsStatTypeRandomPool = ["durability", "attackDamage", "attackSpeed", "miningSpeed"]
		#List of stat types (in order) that will be awarded when leveling up tools. If level is higher than list size the mod will start over.
		#If empty default order will be used (durability, attackDamage, attackSpeed, miningSpeed).
		#Allowed values: durability, attackDamage, attackSpeed, miningSpeed
		toolsStatTypeOrder = ["durability", "attackDamage", "attackSpeed", "miningSpeed"]
		#Set of stat types from which random stat will be awarded when leveling up ranged weapons.
		#If empty default pool will be used (durability, drawSpeed, velocity, accuracy, projectileDamage).
		#Possible values: drawSpeed, velocity, accuracy, projectileDamage, durability, attackDamage, attackSpeed
		rangedStatTypeRandomPool = ["durability", "drawSpeed", "velocity", "accuracy", "projectileDamage"]
		#List of stat types (in order) that will be awarded when leveling up ranged weapons. If level is higher than list size the mod will start over.
		#If empty default rotation will be used (durability, drawSpeed, velocity, accuracy, projectileDamage).
		#Possible values: drawSpeed, velocity, accuracy, projectileDamage, durability, attackDamage, attackSpeed
		rangedStatTypeRotation = ["durability", "drawSpeed", "velocity", "accuracy", "projectileDamage"]
		#Set of stat types from which random stat will be awarded when leveling up armor.
		#If empty default pool will be used (durability, armor, armorToughness, knockbackResistance).
		#Allowed values: durability, armor, armorToughness, knockbackResistance
		armorStatTypeRandomPool = ["durability", "armor", "armorToughness", "knockbackResistance"]
		#List of stat types (in order) that will be awarded when leveling up armor. If level is higher than list size the mod will start over.
		#If empty default order will be used (durability, armor, armorToughness, knockbackResistance).
		#Allowed values: durability, armor, armorToughness, knockbackResistance
		armorStatTypeOrder = ["durability", "armor", "armorToughness", "knockbackResistance"]

		#Tool stat values rewarded on level ups
		[general.stats.toolValues]
			#Range: 1 ~ 1000
			durability = 100
			#Range: 0.1 ~ 10.0
			attackDamage = 1.5
			#Range: 0.1 ~ 10.0
			attackSpeed = 0.5
			#Range: 0.1 ~ 10.0
			miningSpeed = 2.0

		#Ranged weapons stat values rewarded on level ups
		[general.stats.rangedValues]
			#Range: 1 ~ 1000
			durability = 100
			#Range: 0.1 ~ 10.0
			drawSpeed = 0.2
			#Range: 0.1 ~ 10.0
			velocity = 0.2
			#Range: 0.01 ~ 1.0
			accuracy = 0.1
			#Range: 0.1 ~ 10.0
			projectileDamage = 0.2
			#Range: 0.1 ~ 10.0
			attackDamage = 0.5
			#Range: 0.1 ~ 10.0
			attackSpeed = 0.25

		#Armor stat values rewarded on level ups
		[general.stats.armorValues]
			#Range: 1 ~ 1000
			durability = 100
			#Range: 0.1 ~ 10.0
			armor = 0.5
			#Range: 0.1 ~ 10.0
			armorToughness = 0.2
			#Range: 0.1 ~ 1.0
			knockbackResistance = 0.2

#Tool levelling settings
[toolLevelling]
	#Melee only!
	#If true, base experience value gained for attacking is equal to damage dealt (rounded to whole number), otherwise 1.
	damageDealt = true
	#If true, base experience value gained for taking damage is equal to damage taken (rounded to whole number), otherwise 1.
	damageTaken = true
	#If true, base experience value gained for blocking damage is equal to damage blocked (rounded to whole number), otherwise 1.
	damageBlocked = true
	#If true, allows to gain experience from dealing damage to or taking damage from other players.
	pvp = true

	#If true, given action will yield tool experience.
	[toolLevelling.actions]
		mining = true
		harvesting = true
		shearing = true
		stripping = true
		scrapping = true
		waxingOff = true
		tilling = true
		pathMaking = true
		attacking = true
		#Applies to ranged weapons like longbows and crossbows.
		shooting = true
		#Applies to armor only.
		takingDamage = true
		blockingDamage = true
		#Applies to armor only. Thorns modifier gives 15% chance per level to gain experience.
		thorns = true

	#Amount of bonus experience for performing actions. If set to 0 there is no bonus experience.
	[toolLevelling.bonuses]
		#Range: > 0
		mining = 0
		#Range: > 0
		harvesting = 0
		#Range: > 0
		shearing = 0
		#Range: > 0
		stripping = 0
		#Range: > 0
		scrapping = 0
		#Range: > 0
		waxingOff = 0
		#Range: > 0
		tilling = 0
		#Range: > 0
		pathMaking = 0
		#Range: > 0
		attacking = 0
		#Range: > 0
		shooting = 0
		#Range: > 0
		takingDamage = 0
		#Range: > 0
		blockingDamage = 0
		#As with Thorns damage calculations, this is the upper bound of the bonus experience that could be granted.
		#For example, for the value of 3 (default), we get: 1 (base xp) + 0 to 3 (bonus xp) = 1 to 4 (result xp)
		#Range: > 0
		thorns = 3

