
#Chemical Atomizer
[atomizer]
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 100000
	#Default: 50 FE
	#Range: > 0
	energyPerTick = 50
	#Default: 50 ticks
	#Range: > 1
	ticksPerOperation = 50
	#Default: 16000 (16 buckets)
	#Range: > 1
	fluidCapacity = 16000

#Chemical Compactor
[compactor]
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 100000
	#Default: 50 FE
	#Range: > 0
	energyPerTick = 50
	#Default: 50 ticks
	#Range: > 1
	ticksPerOperation = 50

#Chemical Combiner
[combiner]
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 100000
	#Default: 200 FE
	#Range: > 0
	energyPerTick = 200
	#Default: 50 ticks
	#Range: > 1
	ticksPerOperation = 50

#Chemical Dissolver
[dissolver]
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 100000
	#Default: 100 FE
	#Range: > 0
	energyPerTick = 100
	#Default: 50 ticks
	#Range: > 1
	ticksPerOperation = 50

#Chemical Liquifier
[liquifier]
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 100000
	#Default: 50 FE
	#Range: > 0
	energyPerTick = 50
	#Default: 100 ticks
	#Range: > 1
	ticksPerOperation = 100
	#Default: 16000 (16 buckets)
	#Range: > 1
	fluidCapacity = 16000

#Fission
[fission]
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 100000
	#Default: 300 FE
	#Range: > 0
	energyPerTick = 300
	#Default: 50 ticks
	#Range: > 1
	ticksPerOperation = 50

#Fusion
[fusion]
	#Default: 100000 (100k FE)
	#Range: > 0
	energyCapacity = 100000
	#Default: 300 FE
	#Range: > 0
	energyPerTick = 300
	#Default: 50 ticks
	#Range: > 1
	ticksPerOperation = 50

