#Max Energy Stored, range 100 - 100,000,000, default 100,000
#Range: 100 ~ 100000000
maxEnergyStored = 100000
#Ticks per craft in ticks, range 1 - 2048, default 20
#Range: 1 ~ 2048
ticksPerCraft = 20
#Energy per tick of crafting, range 1 - 8192, default 40
#Range: 1 ~ 8192
energyPerTick = 40

