#Need help? Ask on Discord or Github/Gitlab <3 (ps: it is possible that this file contains nothing it's normal)
#Mon Oct 06 20:08:15 CEST 2025
int.villages.spacing=45
int.villages.separation=20
boolean.villages.enabled_custom_config=true
int.villages.salt=10387312
