
#
#    These options are for rendering element abbreviations on different items in your inventory
#    Disable rendering abbreviations on a per item type basis.
#
["Rendering Options"]
	"dust abbreviations" = false
	"nugget abbreviations" = false
	"ingot abbreviations" = false
	"element abbreviations" = true
	"plate abbreviations" = false

