
#lots of cosmetic stuff in here
[visuals]
	#How much the dummy swings in degrees with respect to the damage dealt. default=0.75
	#Range: 0.0 ~ 2.0
	animationIntensity = 0.75
	#Show hearths instead of damage dealt? (1 hearth = two damage)
	showHearths = false
	#Does dps message update dynamically or will it only appear after each parse? 
	#Allowed Values: DYNAMIC, STATIC, OFF
	DPS_mode = "DYNAMIC"
	#Skin used by the dummy
	#Allowed Values: DEFAULT, ORIGINAL, DUNGEONS, ALTERNATIVE
	texture = "DEFAULT"

	[visuals.damage_number_colors]
		#hex color for various damage sources
		genetic = "ffffff"
		crit = "ff0000"
		dragon_breath = "e600ff"
		wither = "666666"
		explosion = "ffbb29"
		magic_indirect = "844ce7"
		magic = "33b1ff"
		trident = "ff9d"
		fire = "ff7700"
		lightning = "fff200"
		cactus = "fa209"
		true_damage = "910038"

