
[general]
	#Wether ghost blocks are shown when you are holding a framed block
	showGhostBlocks = true
	#Wether certain framed blocks should show fancy hitboxes
	fancyHitboxes = true
	#If false only full block faces of framed blocks will be culled, if true all outer faces of famed blocks can be culled
	detailedCulling = true
	#If true, the UV remapping will use discrete steps to avoid floating point errors
	discreteUVSteps = true

[overlay]
	#If set to DETAILED, the State Lock overlay will show detailed info
	#Allowed Values: HIDDEN, ICON, DETAILED
	stateLockMode = "DETAILED"
	#If set to DETAILED, the Toggle Waterloggable overlay will show detailed info
	#Allowed Values: HIDDEN, ICON, DETAILED
	toggleWaterlogMode = "DETAILED"
	#If set to DETAILED, the Toggle Slope Face overlay will show detailed info
	#Allowed Values: HIDDEN, ICON, DETAILED
	toggleYSlopeMode = "DETAILED"
	#If set to DETAILED, the Reinforcement overlay will show detailed info
	#Allowed Values: HIDDEN, ICON, DETAILED
	reinforcedMode = "DETAILED"
	#If set to DETAILED, the Prism Offset overlay will show detailed info
	#Allowed Values: HIDDEN, ICON, DETAILED
	prismOffsetMode = "DETAILED"
	#If set to DETAILED, the Collapsible Block Split Line overlay will show detailed info
	#Allowed Values: HIDDEN, ICON, DETAILED
	splitLineMode = "DETAILED"
	#If set to DETAILED, the One-Way Window overlay will show detailed info
	#Allowed Values: HIDDEN, ICON, DETAILED
	oneWayWindowMode = "DETAILED"
	#If set to DETAILED, the Item Frame Background overlay will show detailed info
	#Allowed Values: HIDDEN, ICON, DETAILED
	itemFrameBackgroundMode = "DETAILED"

