
[GridColors]
	#Normal pipe color. (Hex RGB)
	normal_pipe_color = "A5A5A5"
	#Perforated pipe color. (Hex RGB)
	perforated_pipe_color = "54FF54"
	#Perforated pipe color. (Hex RGB)
	fixed_perforated_pipe_color = "FF515A"

