storagenetwork = true
tconstruct = true
sophisticatedbackpacks = true
fastfurnace = true
ironfurnaces = true
occultism = true
jei = true
ae2 = true
extendedcrafting = true
refinedstorageaddons = true
craftingcraft = true
toms_storage = true
sophisticatedcore = true
refinedstorage = true
prettypipes = true
fastsuite = true
fastbench = true
cyclic = true

