
["UI Button"]
	#X position of the "Open Planner" button. Default: 116
	#Range: -300 ~ 300
	"X Position" = 116
	#Y position of the "Open Planner" button. Default: 18
	#Range: -300 ~ 300
	"Y Position" = 18
	#X position of the "Import Tool" button in the Tinker's Anvil. Default: 34
	#Range: -300 ~ 300
	"Import Tool X Position Anvil" = 34
	#Y position of the "Import Tool" button in the Tinker's Anvil. Default: 60
	#Range: -300 ~ 300
	"Import Tool Y Position Anvil" = 60
	#X position of the "Import Tool" button in the Tinker's Station. Default: 55
	#Range: -300 ~ 300
	"Import Tool X Position Station" = 55
	#Y position of the "Import Tool" button in the Tinker's Station. Default: 60
	#Range: -300 ~ 300
	"Import Tool Y Position Station" = 60

[Planner]
	#The scroll direction for paginated lists
	#Allowed Values: UP, DOWN
	"Scroll Direction" = "DOWN"

