#Ender Cell channel info is only visible to its owner.
onlyOwnerCanSeeEnderChannel = false

[forge]
	#List of mod IDs for which no TOP Addons fluid gauge should be shown
	gaugeModBlacklist = ["mekanism", "mekanismgenerators", "fluidtank", "endertanks"]

[bloodmagic]
	#Seeing blood/incense altar info requires holding a divination or seer sigil in any hand
	altarsRequireSigil = false

