onEvent('recipes', e => {

    //Function for Orechid
    function orechid(input, output, weight) { e.custom({ "type": "botania:orechid", "input": input, "output": { "type": "block", "block": output }, "weight": weight }) }

    orechid('minecraft:deepslate', 'evilcraft:dark_ore_deepslate', 100)
    orechid('minecraft:deepslate', 'ftbic:deepslate_iridium_ore', 125)
    orechid('minecraft:deepslate', 'create:deepslate_zinc_ore', 250)
    orechid('minecraft:deepslate', 'forbidden_arcanus:runic_deepslate', 50)
    orechid('minecraft:deepslate', 'forbidden_arcanus:deepslate_arcane_crystal_ore', 100)
    orechid('minecraft:deepslate', 'thermal:deepslate_apatite_ore', 25)
    orechid('minecraft:deepslate', 'thermal:deepslate_niter_ore', 50)
    orechid('minecraft:deepslate', 'ae2:deepslate_quartz_ore', 200)
    orechid('minecraft:deepslate', 'mekanism:deepslate_fluorite_ore', 200)
    orechid('minecraft:deepslate', 'mekanism:deepslate_uranium_ore', 250)
    orechid('minecraft:deepslate', 'mekanism:deepslate_osmium_ore', 200)
    orechid('minecraft:deepslate', 'thermal:deepslate_tin_ore', 250)
    orechid('minecraft:deepslate', 'powah:deepslate_uraninite_ore', 150)
    orechid('minecraft:deepslate', 'thermal:deepslate_cinnabar_ore', 250)
    orechid('minecraft:deepslate', 'tinkers_reforged:deepslate_aluminum_ore', 200)
    orechid('minecraft:deepslate', 'thermal:deepslate_nickel_ore', 125)
    orechid('minecraft:deepslate', 'thermal:deepslate_silver_ore', 150)
    orechid('minecraft:deepslate', 'thermal:deepslate_lead_ore', 200)
    orechid('minecraft:deepslate', 'thermal:deepslate_sulfur_ore', 250)

    orechid('minecraft:stone', 'powah:uraninite_ore', 10000)
    orechid('minecraft:stone', 'thermal:sulfur_ore', 16000)
    orechid('minecraft:stone', 'ftbic:iridium_ore', 1000)
    orechid('minecraft:stone', 'thermal:cinnabar_ore', 20000)
    orechid('minecraft:stone', 'thermal:apatite_ore', 35000)
    orechid('minecraft:stone', 'thermal:nickel_ore', 19000)
    orechid('minecraft:stone', 'forbidden_arcanus:arcane_crystal_ore', 15000)
    orechid('minecraft:stone', 'create:zinc_ore', 29350)
    orechid('minecraft:stone', 'mekanism:osmium_ore', 20000)
    orechid('minecraft:stone', 'mekanism:uranium_ore', 20000)
    orechid('minecraft:stone', 'evilcraft:dark_ore', 500)
    orechid('minecraft:stone', 'thermal:silver_ore', 29350)
    orechid('minecraft:stone', 'miniutilities:ender_ore', 20000)
    orechid('minecraft:stone', 'thermal:niter_ore', 28000)
    orechid('minecraft:stone', 'thermal:lead_ore', 29350)
    orechid('minecraft:stone', 'mekanism:fluorite_ore', 20000)
    orechid('minecraft:stone', 'tinkers_reforged:aluminum_ore', 29350)
    orechid('minecraft:stone', 'ae2:quartz_ore', 15000)
    orechid('minecraft:stone', 'thermal:tin_ore', 29350)
    orechid('minecraft:stone', 'rftoolsbase:dimensionalshard_overworld', 750)

    orechid('minecraft:end_stone', 'byg:end_sand', 85)
    orechid('minecraft:end_stone', 'tinkers_reforged:kepu_ore', 5)
    orechid('minecraft:end_stone', 'rftoolsbase:dimensionalshard_end', 10)

    orechid('beyond_earth:moon_stone', 'beyond_earth:moon_ice_shard_ore', 5)
    orechid('beyond_earth:moon_stone', 'beyond_earth:moon_iron_ore', 10)
    orechid('beyond_earth:moon_stone', 'beyond_earth:moon_cheese_ore', 70)
    orechid('beyond_earth:moon_stone', 'beyond_earth:moon_desh_ore', 15)

    orechid('beyond_earth:glacio_stone', 'beyond_earth:glacio_coal_ore', 15)
    orechid('beyond_earth:glacio_stone', 'beyond_earth:glacio_copper_ore', 7)
    orechid('beyond_earth:glacio_stone', 'beyond_earth:glacio_iron_ore', 5)
    orechid('beyond_earth:glacio_stone', 'beyond_earth:glacio_lapis_ore', 3)
    orechid('beyond_earth:glacio_stone', 'beyond_earth:glacio_ice_shard_ore', 70)

    orechid('blue_skies:turquoise_stone', 'blue_skies:everbright_diopside_ore', 10)
    orechid('blue_skies:turquoise_stone', 'blue_skies:everbright_pyrope_ore', 10)
    orechid('blue_skies:turquoise_stone', 'blue_skies:everbright_aquite_ore', 10)
    orechid('blue_skies:turquoise_stone', 'blue_skies:everbright_charoite_ore', 10)
    orechid('blue_skies:turquoise_stone', 'blue_skies:everbright_moonstone_ore', 10)
    orechid('blue_skies:turquoise_stone', 'blue_skies:everbright_emerald_ore', 10)
    orechid('blue_skies:turquoise_stone', 'blue_skies:falsite_ore', 10)
    orechid('blue_skies:turquoise_stone', 'blue_skies:ventium_ore', 10)

    orechid('blue_skies:lunar_stone', 'blue_skies:everdawn_diopside_ore', 10)
    orechid('blue_skies:lunar_stone', 'blue_skies:everdawn_pyrope_ore', 10)
    orechid('blue_skies:lunar_stone', 'blue_skies:everdawn_aquite_ore', 10)
    orechid('blue_skies:lunar_stone', 'blue_skies:everdawn_charoite_ore', 10)
    orechid('blue_skies:lunar_stone', 'blue_skies:everdawn_moonstone_ore', 10)
    orechid('blue_skies:lunar_stone', 'blue_skies:everdawn_emerald_ore', 10)
    orechid('blue_skies:lunar_stone', 'blue_skies:horizonite_ore', 10)

    orechid('undergarden:depthrock', 'undergarden:depthrock_coal_ore', 50)
    orechid('undergarden:depthrock', 'undergarden:depthrock_iron_ore', 15)
    orechid('undergarden:depthrock', 'undergarden:depthrock_gold_ore', 10)
    orechid('undergarden:depthrock', 'undergarden:depthrock_diamond_ore', 3)
    orechid('undergarden:depthrock', 'undergarden:depthrock_cloggrum_ore', 15)
    orechid('undergarden:depthrock', 'undergarden:depthrock_utherium_ore', 2)
    orechid('undergarden:depthrock', 'undergarden:depthrock_regalium_ore', 5)

    orechid('undergarden:shiverstone', 'undergarden:shiverstone_coal_ore', 50)
    orechid('undergarden:shiverstone', 'undergarden:shiverstone_iron_ore', 15)
    orechid('undergarden:shiverstone', 'undergarden:shiverstone_diamond_ore', 3)
    orechid('undergarden:shiverstone', 'undergarden:shiverstone_cloggrum_ore', 15)
    orechid('undergarden:shiverstone', 'undergarden:shiverstone_froststeel_ore', 10)
    orechid('undergarden:shiverstone', 'undergarden:shiverstone_utherium_ore', 2)
    orechid('undergarden:shiverstone', 'undergarden:shiverstone_regalium_ore', 5)

})