onEvent('recipes', e => {

    function Singularity(input, output, amount) { e.custom({ "type": "avaritia:compressor", "result": { "item": output }, "cost": amount, "ingredients": [{ "item": input }] }) }

    // Singularity('in', 'out', 4269)

    Singularity('minecraft:raw_gold', 'ragnamod_seven:gold_singularity', 4269)
    Singularity('ae2:fluix_crystal', 'ragnamod_seven:fluix_singularity', 4269)
    Singularity('architects_palette:cerebral_plate', 'ragnamod_seven:cerebral_singularity', 4269)
    Singularity('architects_palette:nether_brass_ingot', 'ragnamod_seven:netherbrass_singularity', 4269)
    Singularity('architects_palette:sunmetal_brick', 'ragnamod_seven:sunmetal_singularity', 4269)
    Singularity('architects_palette:wardstone_brick', 'ragnamod_seven:wardstone_singularity', 4269)
    Singularity('beyond_earth:raw_calorite', 'ragnamod_seven:calorite_singularity', 4269)
    Singularity('beyond_earth:raw_desh', 'ragnamod_seven:desh_singularity', 4269)
    Singularity('beyond_earth:raw_ostrum', 'ragnamod_seven:ostrum_singularity', 4269)
    Singularity('bloodmagic:corrosivecrystal', 'ragnamod_seven:corrosivewill_singularity', 4269)
    Singularity('bloodmagic:defaultcrystal', 'ragnamod_seven:demonwill_singularity', 4269)
    Singularity('bloodmagic:destructivecrystal', 'ragnamod_seven:destructivewill_singularity', 4269)
    Singularity('bloodmagic:steadfastcrystal', 'ragnamod_seven:steadfaswill_singularity', 4269)
    Singularity('bloodmagic:vengefulcrystal', 'ragnamod_seven:vengefulwill_singularity', 4269)
    Singularity('blue_skies:raw_aquite', 'ragnamod_seven:aquite_singularity', 4269)
    Singularity('blue_skies:raw_charoite', 'ragnamod_seven:charoite_singularity', 4269)
    Singularity('blue_skies:raw_falsite', 'ragnamod_seven:falsite_singularity', 4269)
    Singularity('blue_skies:raw_horizonite', 'ragnamod_seven:horizonite_singularity', 4269)
    Singularity('blue_skies:raw_ventium', 'ragnamod_seven:ventium_singularity', 4269)
    Singularity('botania:livingrock', 'ragnamod_seven:livingrock_singularity', 4269)
    Singularity('botania:livingwood_log', 'ragnamod_seven:livingwood_singularity', 4269)
    Singularity('botania:mana_diamond', 'ragnamod_seven:manadiamond_singularity', 4269)
    Singularity('botania:pixie_dust', 'ragnamod_seven:pixie_singularity', 4269)
    Singularity('compactmachines:wall', 'ragnamod_seven:compactmachinewall_singularity', 4269)
    Singularity('create:electron_tube', 'ragnamod_seven:electrontube_singularity', 4269)
    Singularity('create:precision_mechanism', 'ragnamod_seven:precisionmechanism_singularity', 4269)
    Singularity('create_sa:heat_engine', 'ragnamod_seven:heatengine_singularity', 4269)
    Singularity('create_sa:hydraulic_engine', 'ragnamod_seven:hydraulicengine_singularity', 4269)
    Singularity('create_sa:steam_engine', 'ragnamod_seven:steamengine_singularity', 4269)
    Singularity('evilcraft:blood_potash', 'ragnamod_seven:bloodpotash_singularity', 4269)
    Singularity('evilcraft:dark_power_gem', 'ragnamod_seven:darkpower_singularity', 4269)
    Singularity('forbidden_arcanus:arcane_crystal', 'ragnamod_seven:arcanecrystal_singularity', 4269)
    Singularity('forbidden_arcanus:dark_nether_star', 'ragnamod_seven:darknetherstar_singularity', 4269)
    Singularity('forbidden_arcanus:mundabitur_dust', 'ragnamod_seven:mundabitur_singularity', 4269)
    Singularity('ftbic:antimatter', 'ragnamod_seven:antimatter_singularity', 4269)
    Singularity('ftbic:compressed_coal_ball', 'ragnamod_seven:compressedcoalball_singularity', 4269)
    Singularity('ftbic:protein_bar', 'ragnamod_seven:ftbroteinbar_singularity', 4269)
    Singularity('ftbic:scrap', 'ragnamod_seven:scrap_singularity', 4269)
    Singularity('industrialforegoing:fertilizer', 'ragnamod_seven:fertilizer_singularity', 4269)
    Singularity('industrialforegoing:plastic', 'ragnamod_seven:plastic_singularity', 4269)
    Singularity('integrateddynamics:logic_director', 'ragnamod_seven:logicdirector_singularity', 4269)
    Singularity('integrateddynamics:variable', 'ragnamod_seven:variablecard_singularity', 4269)
    Singularity('mekanism:electrolytic_core', 'ragnamod_seven:electrolytic_singularity', 4269)
    Singularity('mekanism:module_base', 'ragnamod_seven:mekasuitmodule_singularity', 4269)
    Singularity('mekanism:raw_osmium', 'ragnamod_seven:osmium_singularity', 4269)
    Singularity('mekanism:reprocessed_fissile_fragment', 'ragnamod_seven:reprocessedfissilefragment_singularity', 4269)
    Singularity('minecraft:amethyst_shard', 'ragnamod_seven:amethyst_singularity', 4269)
    Singularity('minecraft:coal', 'ragnamod_seven:coal_singularity', 4269)
    Singularity('minecraft:diamond', 'ragnamod_seven:diamond_singularity', 4269)
    Singularity('minecraft:emerald', 'ragnamod_seven:emerald_singularity', 4269)
    Singularity('minecraft:redstone', 'ragnamod_seven:redstone_singularity', 4269)
    Singularity('minecraft:ender_pearl', 'ragnamod_seven:enderpearl_singularity', 4269)
    Singularity('minecraft:glowstone_dust', 'ragnamod_seven:glowstone_singularity', 4269)
    Singularity('minecraft:lapis_lazuli', 'ragnamod_seven:lapislazuli_singularity', 4269)
    Singularity('minecraft:netherite_scrap', 'ragnamod_seven:netheritescrap_singularity', 4269)
    Singularity('minecraft:quartz', 'ragnamod_seven:quartz_singularity', 4269)
    Singularity('minecraft:raw_copper', 'ragnamod_seven:copper_singularity', 4269)
    Singularity('minecraft:raw_iron', 'ragnamod_seven:iron_singularity', 4269)
    Singularity('mob_grinding_utils:solid_xp_baby', 'ragnamod_seven:jellybaby_singularity', 4269)
    Singularity('pneumaticcraft:capacitor', 'ragnamod_seven:capacitor_singularity', 4269)
    Singularity('pneumaticcraft:glycerol', 'ragnamod_seven:glycerol_singularity', 4269)
    Singularity('pneumaticcraft:transistor', 'ragnamod_seven:transistor_singularity', 4269)
    Singularity('powah:crystal_blazing', 'ragnamod_seven:blazingcrystal_singularity', 4269)
    Singularity('powah:crystal_niotic', 'ragnamod_seven:nioticcrystal_singularity', 4269)
    Singularity('powah:crystal_nitro', 'ragnamod_seven:nitrocrystal_singularity', 4269)
    Singularity('powah:crystal_spirited', 'ragnamod_seven:spiritedcrystal_singularity', 4269)
    Singularity('powah:steel_energized', 'ragnamod_seven:energizedsteel_singularity', 4269)
    Singularity('powah:uraninite', 'ragnamod_seven:uraninite_singularity', 4269)
    Singularity('psi:ebony_substance', 'ragnamod_seven:ebony_singularity', 4269)
    Singularity('psi:ivory_substance', 'ragnamod_seven:ivory_singularity', 4269)
    Singularity('psi:psigem', 'ragnamod_seven:psigem_singularity', 4269)
    Singularity('reliquary:catalyzing_gland', 'ragnamod_seven:catalyzinggland_singularity', 4269)
    Singularity('reliquary:frozen_core', 'ragnamod_seven:frozencore_singularity', 4269)
    Singularity('reliquary:molten_core', 'ragnamod_seven:moltencore_singularity', 4269)
    Singularity('reliquary:nebulous_heart', 'ragnamod_seven:nebulousheart_singularity', 4269)
    Singularity('reliquary:zombie_heart', 'ragnamod_seven:zombieheart_singularity', 4269)
    Singularity('tconstruct:raw_cobalt', 'ragnamod_seven:cobalt_singularity', 4269)
    Singularity('thermal:basalz_rod', 'ragnamod_seven:basalz_singularity', 4269)
    Singularity('thermal:blitz_rod', 'ragnamod_seven:blitz_singularity', 4269)
    Singularity('thermal:blizz_rod', 'ragnamod_seven:blizz_singularity', 4269)
    Singularity('thermal:rosin', 'ragnamod_seven:rosin_singularity', 4269)
    Singularity('thermal:slag', 'ragnamod_seven:slag_singularity', 4269)
    Singularity('twilightforest:alpha_yeti_fur', 'ragnamod_seven:alphayeti_singularity', 4269)
    Singularity('twilightforest:carminite', 'ragnamod_seven:carminite_singularity', 4269)
    Singularity('twilightforest:magic_beans', 'ragnamod_seven:magicbeans_singularity', 4269)
    Singularity('twilightforest:raw_ironwood', 'ragnamod_seven:ironwood_singularity', 4269)
    Singularity('twilightforest:steeleaf_ingot', 'ragnamod_seven:steeleaf_singularity', 4269)
    Singularity('undergarden:raw_cloggrum', 'ragnamod_seven:cloggrum_singularity', 4269)
    Singularity('undergarden:raw_froststeel', 'ragnamod_seven:froststeel_singularity', 4269)
    Singularity('warden_and_sculk:sculk_block', 'ragnamod_seven:sculk_singularity', 4269)
    Singularity('undergarden:utherium_crystal', 'ragnamod_seven:utherium_singularity', 4269)
    Singularity('undergarden:forgotten_nugget', 'ragnamod_seven:forgotten_singularity', 4269)
    Singularity('undergarden:regalium_crystal', 'ragnamod_seven:regalium_singularity', 4269)

    // Singularity('mekanism:raw_uranium', 'ragnamod_seven:uranium_singularity', 4269)
    // Singularity('dustrial_decor:cast_iron_billet', 'ragnamod_seven:castiron_singularity', 4269)
    // Singularity('create:sturdy_sheet', 'ragnamod_seven:sturdysheet_singularity', 4269)
    // Singularity('blue_skies:diopside_gem', 'ragnamod_seven:diopside_singularity', 4269)
    // Singularity('blue_skies:pyrope_gem', 'ragnamod_seven:pyrope_singularity', 4269)
    // Singularity('twilightforest:castle_brick', 'ragnamod_seven:castlebrick_singularity', 4269)
    // Singularity('thermal:sulfur', 'ragnamod_seven:sulfur_singularity', 4269)
    // Singularity('thermal:bitumen', 'ragnamod_seven:bitumen_singularity', 4269)
    // Singularity('thermal:cinnabar', 'ragnamod_seven:cinnabar_singularity', 4269)
    // Singularity('thermal:niter', 'ragnamod_seven:niter_singularity', 4269)
    // Singularity('reliquary:rib_bone', 'ragnamod_seven:ribbone_singularity', 4269)
    // Singularity('reliquary:chelicerae', 'ragnamod_seven:chelicerae_singularity', 4269)
    // Singularity('dustrial_decor:industrial_iron_billet', 'ragnamod_seven:industrialiron_singularity', 4269)
    // Singularity('architects_palette:oracle_jelly', 'ragnamod_seven:oraclejelly_singularity', 4269)
    // Singularity('architects_palette:algal_brick', 'ragnamod_seven:algal_singularity', 4269)
    // Singularity('undergarden:depthrock_pebble', 'ragnamod_seven:depthrock_singularity', 4269)
    // Singularity('tinkers_reforged:raw_aluminum', 'ragnamod_seven:bauxite_singularity', 4269)
    // Singularity('tinkers_reforged:raw_kepu', 'ragnamod_seven:kepu_singularity', 4269)
    // Singularity('thermal:raw_lead', 'ragnamod_seven:lead_singularity', 4269)
    // Singularity('thermal:raw_nickel', 'ragnamod_seven:nickel_singularity', 4269)
    // Singularity('thermal:raw_silver', 'ragnamod_seven:silver_singularity', 4269)
    // Singularity('thermal:raw_tin', 'ragnamod_seven:tin_singularity', 4269)
    // Singularity('spirit:soul_powder_block', 'ragnamod_seven:soulpowder_singularity', 4269)
    // Singularity('naturesaura:infused_stone', 'ragnamod_seven:infusedrock_singularity', 4269)
    // Singularity('occultism:spirit_attuned_gem', 'ragnamod_seven:spiritattunedgem_singularity', 4269)
    // Singularity('infernalexp:glowcoal', 'ragnamod_seven:glowcoke_singularity', 4269)
    // Singularity('industrialforegoing:pink_slime_ingot', 'ragnamod_seven:pinkslime_singularity', 4269)
    // Singularity('create:raw_zinc', 'ragnamod_seven:zinc_singularity', 4269)
    // Singularity('buildinggadgets:construction_paste', 'ragnamod_seven:constructionpaste_singularity', 4269)
    // Singularity('ars_nouveau:source_gem', 'ragnamod_seven:sourcegem_singularity', 4269)
    // Singularity('byg:raw_pendorite', 'ragnamod_seven:pendorite_singularity', 4269)

})